def sum(x):
  21

let a = 1 in try sum(5) catch RuntimeException as e in raise(e)