def throw(x):
  raise(RuntimeException)

try throw(5) catch RuntimeException as e in 5